### ISSUE TITLE
Repository location

### ISSUE THREAD

**Issue by alexey-kravtsov-tc** [emitchel/AndroidMVVMCoroutines#3]
Hi! Great MVVM showcase! 

One small question - do you have a particular reason why to store repositories(especially ```ArtistRepository``` interface) in the Data folder? Is there no need for the domain layer in your app?

Thanks! Keep it up :)

**Comment by emitchel** [comment]
No particular reason; with it being the only repository, I didn't think much of it. How do you envision the domain layer?

**Comment by alexey-kravtsov-tc** [comment]
Not big of a deal, just curious why repository belongs to the data layer.
Not clear for me why do you have ArtistRepository interface then, if even in tests you are mocking BandsInTownArtistRepository

**Comment by emitchel** [comment]
@alexkrafts that's a good point, at the time of messing around with tests I was seeing how close I could get to the implementation. There's no real reason for the interface other than to describe the contract at a high level.
